export const site = {
  name: 'Sarva Mangala Jothida Nilayam',
  nameTamil: 'சர்வ மங்கள ஜோதிட நிலையம்',
  tagline: 'Traditional Vedic Astrology — Salem',
  founder: 'Dr. Elangho Thirunavukkarasu',
  founderTamil: 'முனைவர். இளங்கோ திருநாவுக்கரசு',
  honorific: 'Mithuna Rishi',
  degrees: 'B.Sc., M.A., M.Ed., M.A., M.Phil., M.A., Ph.D. (Astro)',
  teamName: 'Sarva Mangala Jothida Nilayam',
  phones: ['+91 99766 48444', '+91 73 73 273 273'],
  whatsapp: '919976648444',
  email: '',
  address: [
    '3/131-A, Dharshini Nagar, Ratna Garden 1st Street',
    'Opposite Salem Government Medical College, Steel Plant Road',
    'S. Kollapatti (PO), Salem 636 030, Tamil Nadu, India',
  ],
  addressTamil: [
    '3/131-A, தர்ஷினி நகர், ரத்னா கார்டன் முதல் வீதி',
    'சேலம் அரசு மருத்துவக் கல்லூரி எதிரில், இரும்பாலை ரோடு',
    'S.கொல்லப்பட்டி (PO), சேலம் 636 030',
  ],
  youtube: 'https://www.youtube.com',
  channel: 'Mithuna Rishi Astro Channel',
  channelTamil: 'மிதுன ரிஷி அஸ்ட்ரோ சேனல்',
  gstRate: 0.18,
  currency: 'INR',
  logo: '/logo.jpg',
  portrait: '/images/brand/professional-portrait.png',
  portraitAlt: '/images/profile/photo_2026-08-15_06-13-11.jpg',
  banner: '/images/brand/professional-banner.png',
  videos: [
    { src: '/videos/what-is-astrology.mp4', title: 'What is Astrology?' },
    { src: '/videos/love-marriage.mp4', title: 'Love & Marriage' },
    { src: '/videos/child-birthchart.mp4', title: 'Child Birth Chart' },
    { src: '/videos/directions.mp4', title: 'Directions & Guidance' },
  ],
  awards: [
    {
      src: '/images/awards/jyotish-vachaspati-2016.jpeg',
      title: 'Jyotisha Vachaspati',
      year: '2016',
      detail: 'Special title in astrology — SASTRA, Madurai. M.A. (Astrology), Annamalai University. Erode, 18 Dec 2016.',
    },
    {
      src: '/images/awards/annamalai-ma-astrology-plaque.jpeg',
      title: 'M.A. (Astrology)',
      year: 'Annamalai University',
      detail: 'Awarded in collaboration with Saptharishi Astrological Sciences Training and Research Academy, Madurai. Enrollment 82114DR092.',
    },
    {
      src: '/images/awards/phd-amcc-calcutta-2018.jpeg',
      title: 'Ph.D. (Astrology)',
      year: '2018',
      detail: 'Doctor of Philosophy in Astrology — Alternative Medical Council Calcutta, 29 Jan 2018.',
    },
    {
      src: '/images/awards/phd-medicina-alternativa-2018.jpeg',
      title: 'Ph.D. (Astrology)',
      year: '2018',
      detail: 'Doctor of Philosophy (Astrology) — Medicina Alternativa / Open International University for Complementary Medicines, Colombo, January 2018.',
    },
    {
      src: '/images/awards/jothida-samrat-certificate-2018.jpeg',
      title: 'Jothida Samrat',
      year: '2018',
      detail: 'Emperor of Astrology — All India Astrologer Conference, Sakthi Mahal, Erode, 11–12 Aug 2018. Conferred on Mithuna Rishi Dr. T. Elangho.',
    },
    {
      src: '/images/awards/jothida-samrat-plaque-2018.jpeg',
      title: 'Jothida Samrat Plaque',
      year: '2018',
      detail: 'Commemorative plaque for the Jothida Samrat honour at the All India Astrologer Conference.',
    },
    {
      src: '/images/awards/jyotisha-vitthakar-2023.jpeg',
      title: 'Jyothisha Vitthagar',
      year: '2023',
      detail: 'World Tamil Astrologers Maha Jana Sabhai — 12th Astrology Conference, Malligai Arangam, Erode, 16–17 Dec 2023.',
    },
    {
      src: '/images/awards/traditional-expert-plaque-2025.jpeg',
      title: 'Traditional Astrology Expert',
      year: '2025',
      detail: 'Paarambariya Jothida Vitthagar — All World True Astrologers Association & Mahajeyam Astro Research, Erode, 6 Apr 2025.',
    },
  ],
  gallery: [
    { src: '/images/gallery/family-convocation.jpeg', alt: 'Family at convocation' },
    { src: '/images/gallery/felicitation-tamil-astrologers-2023.jpeg', alt: 'Felicitation — Tamil astrologers, 2023' },
    { src: '/images/gallery/india-astrologer-conference.jpeg', alt: 'India Astrologer Conference' },
    { src: '/images/gallery/sastra-annamalai-ceremony.jpeg', alt: 'SASTRA — Annamalai ceremony' },
    { src: '/images/gallery/world-tamil-astrologers-event.jpeg', alt: 'World Tamil Astrologers event' },
    { src: '/images/profile/photo_2026-08-15_06-13-14.jpg', alt: 'Dr. Elangho Thirunavukkarasu' },
    { src: '/images/profile/photo_2026-08-15_06-13-17.jpg', alt: 'Dr. Elangho Thirunavukkarasu' },
  ],
}
